### ISSUE TITLE
JavaScript functional programming basics - error

### ISSUE THREAD

**Issue by p0ye** [MeetMartin/lambda#3]
On this [page](https://www.7urtle.com/javascript-functional-programming-basics),
 I believe 
    `const addDonatelo = currentCounter => tortoises + ' and Donatelo';` 
should be something like
    `const addDonatelo = currentCounter => currentCounter + ' and Donatelo';`

**Comment by MeetMartin** [comment]
Thank you @p0ye for noticing the issue and reporting it, I have just pushed the fix.
